"""add_family_fields_to_membership_requests

Revision ID: 4519966f689d
Revises: 0a0218a2ffc7
Create Date: 2026-06-25 10:04:42.901622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4519966f689d'
down_revision: Union[str, Sequence[str], None] = '0a0218a2ffc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('family_relation', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_membership_requests_families', 'families', ['family_id'], ['family_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_membership_requests_families', type_='foreignkey')
        batch_op.drop_column('family_relation')
        batch_op.drop_column('family_id')

    # ### end Alembic commands ###
