"""Add EventPass model

Revision ID: 52bd0a74516f
Revises: e853843829c4
Create Date: 2026-06-21 21:42:58.706864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bd0a74516f'
down_revision: Union[str, Sequence[str], None] = 'e853843829c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_passes',
    sa.Column('pass_id', sa.Uuid(), nullable=False),
    sa.Column('registration_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('qr_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('UNUSED', 'USED', name='pass_status'), nullable=False),
    sa.Column('whatsapp_message_sid', sa.String(length=100), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['event_registrations.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pass_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_passes')
    # ### end Alembic commands ###
