"""Event Booking Branching Logic

Revision ID: e853843829c4
Revises: 01a220772c91
Create Date: 2026-06-21 20:57:17.561815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e853843829c4'
down_revision: Union[str, Sequence[str], None] = '01a220772c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('NOT_APPLICABLE', 'PENDING', 'PAID', 'VERIFIED', 'FAILED', 'REFUNDED', name='payment_status'),
               existing_nullable=False)

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('NOT_APPLICABLE', 'PENDING', 'PAID', 'VERIFIED', 'FAILED', 'REFUNDED', name='payment_status'),
               existing_nullable=False)

    with op.batch_alter_table('email_otp_requests', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_email_otp_requests_email'), ['email'], unique=False)

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('guest_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('guest_email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('payment_mode', sa.Enum('PAY_ONLINE', 'PAY_AT_VENUE', name='event_payment_mode'), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('NOT_APPLICABLE', 'PENDING', 'PAID', 'VERIFIED', 'FAILED', 'REFUNDED', name='payment_status'),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.Enum('OPEN_TO_ALL', 'MEMBERS_ONLY', name='event_visibility'), nullable=False))
        batch_op.add_column(sa.Column('pricing_type', sa.Enum('FREE', 'PAID', name='event_pricing_type'), nullable=False))
        batch_op.drop_column('is_members_only')

    with op.batch_alter_table('phone_otp_requests', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_phone_otp_requests_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_otp_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_otp_requests_phone'))
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_members_only', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_column('pricing_type')
        batch_op.drop_column('visibility')

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.Enum('NOT_APPLICABLE', 'PENDING', 'PAID', 'VERIFIED', 'FAILED', 'REFUNDED', name='payment_status'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.drop_column('payment_mode')
        batch_op.drop_column('guest_email')
        batch_op.drop_column('guest_phone')
        batch_op.drop_column('guest_name')

    with op.batch_alter_table('email_otp_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_otp_requests_email'))
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.Enum('NOT_APPLICABLE', 'PENDING', 'PAID', 'VERIFIED', 'FAILED', 'REFUNDED', name='payment_status'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.Enum('NOT_APPLICABLE', 'PENDING', 'PAID', 'VERIFIED', 'FAILED', 'REFUNDED', name='payment_status'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
